### ISSUE TITLE
`!IDF_TARGET_ESP32` fails to exclude information in ESP-IDF docs for ESP32 (IDFGH-11355)

### ISSUE THREAD

**Issue by f-hollow** [espressif/esp-idf-kconfig#2]
In the ESP-IDF docs, the parameter [ESP_TIMER_INTERRUPT_LEVEL](https://github.com/espressif/esp-idf/blob/master/components/esp_timer/Kconfig#L39) description has the following code:

```sh
        range 1 3 if IDF_TARGET_ESP32
        range 1 1 if !IDF_TARGET_ESP32
```

However, the resulting [document](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-esp-timer-interrupt-level) built for the ESP32 target contains both the included and excluded lines.

ESP-IDF docs built locally exhibit the same issue.

It would be great if you could fix it.

**Comment by peterdragun** [comment]
Hi, thanks for reporting the issue, we will take a look and fix it ASAP.

**Comment by f-hollow** [comment]
The issue is gone now. Thanks a lot!
