### ISSUE TITLE
AttributeError: module 'menuconfig' has no attribute '_main' (IDFGH-12968)

### ISSUE THREAD

**Issue by stkw0** [espressif/esp-idf-kconfig#6]
When switching from esp-idf-kconfig 2.2.0 I got the next error (not that if I downgrade it to esp-idf-kconfig 2.1.0 it works correctly again):

```
[0/1] cd <redacted>/build && /usr/lib/python-exec/python3.1...IDF_INIT_VERSION=5.2.0 --output config <redacted>/sdkconfig
TERM environment variable is set to "alacritty"
Traceback (most recent call last):
  File "/usr/share/esp-idf/tools/kconfig_new/menuconfig_wrapper.py", line 60, in <module>
    main()
  File "/usr/share/esp-idf/tools/kconfig_new/menuconfig_wrapper.py", line 17, in main
    menuconfig._main()
    ^^^^^^^^^^^^^^^^
AttributeError: module 'menuconfig' has no attribute '_main'
```

I'm using:
 - python 3.12
 - esp-idf 5.2.2

**Comment by Honza0297** [comment]
Hello @stkw0! 
Can I ask you how did you get esp-idf-kconfig v 2.2.0? 
ESP IDF 5.2 only supports esp-idf-kconfig version >=1.4.2 and <2.0.0

**Comment by stkw0** [comment]
Hi! Thank you for the information
I maintain the esp-idf package for Gentoo. While packaging the new esp-idf v5.2.2 I also bumped their dependencies according to tools/requirements/requirements.core.txt file on esp-idf repository.
Is there some document I should check in the future before updating the distribution package to be aware of any such version dependencies?

**Comment by Honza0297** [comment]
You can use dependency files downloaded by install scripts. For IDF 5.2, the link is [https://dl.espressif.com/dl/esp-idf/espidf.constraints.v5.2.txt](https://dl.espressif.com/dl/esp-idf/espidf.constraints.v5.2.txt )

Feel free to change the version in the link to get other files as well (master branch corresponds to the next "unpublished" version, currently, it is espidf.constraints.v5.4.txt).

**Comment by stkw0** [comment]
Thank you very much

**Comment by Honza0297** [comment]
This issue will be closed in a short time, but feel free to reopen or open a new issue if you have any future problems.
Good luck with maintaining esp-idf for Gentoo!
